#!/usr/bin/perl

$a = $ARGV[0];
$b = $ARGV[1];
$line = "";

for ($i = $a; $i <= $b; $i++) {
    $line = $line." $i ";
    }

print "Please copy and paste the following line into the command prompt:\n";
print "qdelrj $line\n";

